session_name: dotfiles
global_options:
  automatic-rename: 'off'
start_directory: ~/.dotfiles
windows:
- window_name: dotfiles
  layout: even-vertical
  focus: true
  panes:
  - focus: true
  - pane
- window_name: nvim
  layout: even-vertical
  start_directory: ~/.config/nvim/
  panes:
    - nvim
- window_name: lvim
  layout: even-vertical
  start_directory: ~/.config/lvim/
  panes:
    - focus: true
