session_name: "gridadmin"
global_options:
  automatic-rename: 'off'
windows:
- window_name: shells
  focus: true
  layout: tiled
  start_directory: ~/Developer/ubelix/puppet-installer/controlrepo
  panes:
    - pane
    - shell_command:
      - sudo su -
      - clear
    - pane
    - shell_command:
      - sudo su -
      - clear
      focus: true
- window_name: ems11
  options:
    main-pane-width: 50%
  layout: tiled
  start_directory: ~/
  panes:
    - shell_command:
      - ssh ems11-adm
      - watch -n 5 "mmgetstate -N gss_ppc64,cesnodes"
    - shell_command:
      - ssh ems11-adm
      - watch -n 5 "mmdsh -N gss_ppc64,cesnodes uptime | sort"
    - shell_command:
      - ssh ems11-adm
      focus: true
