---
default: true
MD003: {style: "atx"}
MD013: {line_length: 80, tables: false, code_blocks: false}
MD024: {siblings_only: true}
MD026: {punctuation: ",;:。，；："}
MD033: {allowed_elements: [small, sub, sup]}
MD036: false
