#!/usr/bin/env bash
#
# bootstrap installs dotfiles

stowables="
  alacritty
  asciinema
  bash
  bat
  editorconfig
  git
  homebrew
  karabiner
  scripts
  starship
  tmux
  vbox
  vim
  wget
  yamllint
"

cd "$(dirname "$0")"
DOTFILES_ROOT_ABS=$(pwd -P)

set -e

source "$DOTFILES_ROOT_ABS"/shell_functions.sh

echo ""
info "Installing dotfiles..."

if ! stow -V &>/dev/null
then
  fail "GNU stow not found in PATH"
  exit 1
fi

for stowable in $stowables
do
  if stow -R "$stowable"; then
    success "$stowable"
  else
    warning "$stowable"
  fi
done

echo ""
echo "  Everything in place, have fun!"

exit 0
