#!/usr/bin/env bash
#
# bootstrap installs dotfiles and
# runs every installer found..
#

stowables="
  asciinema
  bash
  bat
  editorconfig
  git
  homebrew
  karabiner
  neovim
  oh-my-posh
  scripts
  tmux
  vbox
  vim
  wget
  yamllint
"

cd "$(dirname "$0")"
DOTFILES_ROOT_ABS=$(pwd -P)
DOTFILES_ROOT_REL=${DOTFILES_ROOT_ABS#$HOME/}

set -e

source $DOTFILES_ROOT_ABS/shell_functions.sh

function check_requirements {
  local err=0

  if ! stow -V &>/dev/null
  then
    fail "GNU stow not found in PATH"
    err=1
  fi

  [ $err -ne 0 ] && exit 1
  return 0
}

function run_installers() {
  # Start with Homebrew as installers might depend on brew installed software
  homebrew_installer="${DOTFILES_ROOT_ABS}/homebrew/install.$(uname -s).sh"
  [ -x $homebrew_installer ] && $homebrew_installer

  # Find all general and platform-specific installers and execute them
  for installer in ${DOTFILES_ROOT_ABS}/*/install{,.$(uname -s)}.sh
  do
    # Skip Homebrew as it's already done
    [[ "${installer}" =~ homebrew ]] && continue
    bash -c $installer
  done
}

check_requirements

prompt_confirm "Shall the installers run (y/n)?" && (info "Running installers..." ; run_installers)

echo ""
info "Installing dotfiles..."
for stowable in $stowables
do
  stow -R --ignore install.*sh $stowable && success $stowable || warning $stowable
done

echo ""
echo "  Everything in place, have fun!"

exit 0

