cask_args appdir: '/Applications'

tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'rbenv'
brew 'rbenv-bundler'
brew 'rbenv-gemset'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'git'
brew 'ack'
brew 'mas'
brew 'packer'
brew 'p7zip'
brew 'ssh-copy-id'
brew 'watch'
brew 'wget'
brew 'bundler-completion'
brew 'packer-completion'
brew 'vagrant-completion'

cask 'font-menlo-for-powerline'
caks 'google-chrome'
cask 'iterm2'
