#!/usr/bin/env bash

cd ~
# Link in files, replacing whatever's already there.
ln -fs ".dotfiles/bash/bashrc"                "${HOME}/.bashrc"
ln -fs ".dotfiles/bash/bash_profile"          "${HOME}/.bash_profile"
#ln -fs ".dotfiles/bash/bash_logout"          "${HOME}/.bash_logout"
ln -fs ".dotfiles/git/gitconfig"              "${HOME}/.gitconfig"
ln -fs ".dotfiles/git/gitmessage"             "${HOME}/.gitmessage"
ln -fs ".dotfiles/git/gitignore_global"       "${HOME}/.gitignore_global"
#ln -fs ".dotfiles/readline/inputrc"          "${HOME}/.inputrc"
ln -fs ".dotfiles/tmux/tmux.conf"             "${HOME}/.tmux.conf"
ln -fs ".dotfiles/vim/vimrc"                  "${HOME}/.vimrc"

# Link in directories, removing whatever's already there first.
[[ -e "${HOME}/.vim" ]] && rm -r "${HOME}/.vim"
ln -fs ".dotfiles/vim" "${HOME}/.vim"
[[ -e "${HOME}/.bash_completion.d" ]] && rm -r "${HOME}/.bash_completion.d"
ln -fs ".dotfiles/bash/completion.d" "${HOME}/.bash_completion.d"

# Fetch packer completion
curl -L https://raw.githubusercontent.com/mrolli/packer-bash-completion/master/packer -o ~/.bash_completion.d/packer

# Finally setup vim plugins and color schemes
~/.vim/setup_vim_env.sh
