#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"

# find the installers and run them iteratively
#find . -depth 2 -name install.sh | while read installer; do bash -c "${installer}"; done
find . -depth 2 -name install.sh -exec bash -c {} \;

cd - >/dev/null

