"Use Vim settings, rather then Vi settings (much better!).
"This must be first, because it changes other options as a side effect.
set nocompatible

"activate pathogen
call pathogen#infect()
call pathogen#helptags()

"first of all change leader to something more
"convenient on a sg keyboard
let mapleader = ","

"load ftplugins and indent files
filetype plugin on
filetype indent on

"turn on syntax highlighting
syntax on

"tell the term has 256 colors
if has("gui_running")
    colorscheme bubblegum
elseif &t_Co == 256
    colorscheme bubblegum
endif

" always display status line
set laststatus=2

"airline configuration
let g:airline_theme='bubblegum'

"syntastic configuration
let g:syntastic_aggregate_errors = 1
let g:syntastic_enable_signs=1
let g:syntastic_auto_loc_list=1
let g:syntastic_puppet_puppetlint_args = "--no-80chars-check --no-class_inherits_from_params_class-check --no-autoloader_layout-check"

"signify configuration
let g:signify_vcs_list = [ 'git' ]

"allow backspacing over everything in insert mode
set backspace=indent,eol,start

"store lots of :cmdline history
set history=1000

set showcmd     "show incomplete cmds down the bottom
set showmode    "show current mode down the bottom
set showmatch   "set show matching parenthesis
set number      "show line numbers
set scrolloff=3 "scroll that many lines if cursor leaves viewport

"highlight tabs and trailing spaces
highlight LiteralTabs ctermbg=red guibg=red
autocmd ColorScheme * highlight LiteralTabs ctermbg=red guibg=red
match LiteralTabs /\s\    /
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

"some key assignments
nnoremap <F2> :buffers<CR>:buffer<Space>
nnoremap <F3> :set invpaste paste?<CR>
set pastetoggle=<F3>

set incsearch   "find the next match as we type the search
set hlsearch    "hilight searches by default
set ignorecase  "ignore case when searching

set wrap        "dont wrap lines
set linebreak   "wrap lines at convenient points

" Swap files in a central location, no swap files amongst project.
set backupdir=~/.vim/swap//
set directory=~/.vim/swap//
set undodir=~/.vim/undofiles//
set undofile

" Default to Unicode/UTF-8 rather than latin1
set encoding=utf-8

"default indent settings
set shiftwidth=2
set softtabstop=2
"set tabstop=8
set expandtab
set autoindent
"set cindent           "recommended seting for automatic C-style indentation

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

set wildmode=list:longest   "make cmdline tab completion similar to bash
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing

"vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

"some stuff to get the mouse going in term
"set mouse=a
"set ttymouse=xterm2

"hide buffers when not displayed
set hidden


"jump to last cursor position when opening a file
"dont do it when writing a commit log entry
autocmd BufReadPost * call SetCursorPosition()
function! SetCursorPosition()
    if &filetype !~ 'svn\|commit\c'
        if line("'\"") > 0 && line("'\"") <= line("$")
            exe "normal! g`\""
            normal! zz
        endif
    end
endfunction

" Don't add the comment prefix when I hit enter or o/O on a comment line.
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" configure NERDTree
map <C-n> :NERDTreeToggle<CR>
"close vim if NERDTree is the last open buffer
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Arrow keys navigate split windows!
nmap <Up> <C-W><Up>
nmap <Down> <C-W><Down>
nmap <Left> <C-W><Left>
nmap <Right> <C-W><Right>

" Reselect visual block after indent (thanks @twe4ked)
vnoremap < <gv
vnoremap > >gv

if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif

" TexLive stuff
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

