#!/usr/bin/env bash

# macOS configuration
#
# This configuration applies to the latest version of macOS (currently 13.1),
# and sets up preferences and configurations for all the built-in services and
# apps. Third-party app config should be done elsewhere.
#
# Options:
#   --no-restart: Don't restart any apps or services after running the script.
#
# If you want to figure out what default needs changing, do the following:
#
#   1. `cd /tmp`
#   2. Store current defaults in file: `defaults read > before`
#   3. Make a change to your system.
#   4. Store new defaults in file: `defaults read > after`
#   5. Diff the files: `diff before after`
#
# @see: http://secrets.blacktree.com/?showapp=com.apple.finder
# @see: https://github.com/herrbischoff/awesome-macos-command-line
#
# @author Michael Rolli
#   based on the very same file of Jeff Geerling. Kudos

# Warn that some commands will not be run if the script is not run as root.
if [[ $EUID -ne 0 ]]; then
  RUN_AS_ROOT=false
  printf "Certain commands will not be run without sudo privileges. To run as root, run the same command prepended with 'sudo', for example: $ sudo $0\n\n" | fold -s -w 80
else
  RUN_AS_ROOT=true
  # Update existing `sudo` timestamp until `.macos` has finished
  while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
  done 2>/dev/null &
fi

# Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set system appearance theme to dark mode
defaults write -g AppleInterfaceStyle "Dark"

# But then change some applications back to light
# To find the the app's ID use the following command; example for Apple Mail
#   osascript -e 'id of app "Mail"'
lightApps=(
  com.apple.Mail
  com.apple.Safari
  com.microsoft.Word
)

for lightApp in ${lightApps[0]}; do
  defaults write "${lightApp}" NSRequiresAquaSystemAppearance -bool true
done

# Always show scrollbar by default; OS default: Automatic
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

# Save to disk (not to iCloud) by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable a lot auto-correction stuff; default: absent
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticTextCompletionEnabled -bool true
defaults wirte NSGlobalDomain NSAutomaticInlinePredictionEnabled -bool false

# Restart automatically if the computer freezes
if [[ "$RUN_AS_ROOT" = true ]]; then
  systemsetup -setrestartfreeze on
fi

# Set timezone to Europe/Zurich; see `systemsetup -listtimezones` for other values
if [[ "$RUN_AS_ROOT" = true ]]; then
  systemsetup -settimezone Europe/Zurich &>/dev/null
fi

# Disable the sound effects on boot
if [[ "$RUN_AS_ROOT" = true ]]; then
  nvram SystemAudioVolume=" "
fi

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Set background to dark-grey color
# TODO: Set my background here?
#osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/System/Library/Desktop Pictures/Solid Colors/Stone.png"'

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Trackpad: Haptic feedback (light, silent clicking)
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
defaults write com.apple.AppleMultitouchTrackpad ActuationStrength -int 0

# Trackpad: Enable tap to click; OS default: false
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

# Trackpad: Disable natural scroll direction; OS default: true
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# Turn F1, F2, ... to standard function keys. Use function key to get the function key
# to get the special function like volume and brightness control; OS default: false
defaults write NSGlobalDomain com.apple.keyboard.fnState -bool true

# Trackpad: Enable App Exposé gesture; OS default: false
defaults write com.apple.dock showAppExposeGestureEnabled -bool true

# Disable press-and-hold for keys in favor of key repeat
#defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate, and make it happen more quickly.
# (The KeyRepeat option requires logging out and back in to take effect.)
defaults write NSGlobalDomain InitialKeyRepeat -int 20
defaults write NSGlobalDomain KeyRepeat -int 1

# Show text input menu in menu bar
defaults write com.apple.TextInputMenu visible -bool true

# Show VPN menu in menu bar and show connection duration
defaults write "NSStatusItem Visible com.apple.menuextra.vpn" "com.apple.systemuiserver" -bool true
defaults write "menuExtras" "com.apple.systemuiserver" '("/System/Library/CoreServices/Menu Extras/VPN.menu",)'
defaults write "com.apple.networkConnect" '{VPNShowTime=1;}'

# Show time machine menu in menu bar
defaults write "NSStatusItem Visible com.apple.menuextra.TimeMachine" "com.apple.systemuiserver" -bool true
defaults write "menuExtras" "com.apple.systemuiserver" '("/System/Library/CoreServices/Menu Extras/VPN.menu","/System/Library/CoreServices/Menu Extras/TimeMachine.menu",)'

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

###############################################################################
# Screen                                                                      #
###############################################################################

# Save screenshots to Documents folder; OS default: Desktop
defaults write com.apple.screencapture location -string "${HOME}/Documents/Screenshots"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true

###############################################################################
# Finder                                                                      #
###############################################################################

# Sync the Documents folder automatically to the iCloud Drive
defaults write com.apple.finder FXICloudDriveDesktop -bool true

# Sync the Desktop folder automatically to the iCloud Drive
defaults write com.apple.finder FXICloudDriveDocuments -bool true

# Set the default location for new Finder windows
# For Desktop paths, use `PfDe` and `file://${HOME}/Desktop/`
# For Home folder, use `PfHm` and `file://${HOME}/`
# For other paths, use `PfLo` and `file:///full/path/here/`
#defaults write com.apple.finder NewWindowTarget -string "PfDe"
#defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Downloads/"

# Disable window animations and Get Info animations; required by yabai
defaults write com.apple.finder DisableAllAnimations -bool true

# Show icons for hard drives, servers, and removable media on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Show hidden files by default
#defaults write com.apple.finder AppleShowAllFiles -bool true

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

# Show path bar
defaults write com.apple.finder "ShowPathbar" -bool "true"

# Show status bar
defaults write com.apple.finder "ShowStatusBar" -bool true

# Allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# Display full POSIX path as Finder window title
#defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# When performing a search, search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Enable spring loading for directories
#defaults write NSGlobalDomain com.apple.springing.enabled -bool true

# Remove the spring loading delay for directories
#defaults write NSGlobalDomain com.apple.springing.delay -float 0.1

# Avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Enable snap-to-grid for icons on the desktop and in other icon views
#/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# Set the size of icons on the desktop and in other icon views
#/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist

# Use column view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

# Disable the warning before emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

# Empty Trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# Dock position; left, bottom, right
defaults write com.apple.dock "orientation" -string "left"

# Automatically hide the Dock and disable Dock animation
defaults write com.apple.dock "autohide" -bool "true"
defaults write com.apple.dock "autohide-time-modifier" -float "0"
defaults write com.apple.dock "autohide-delay" -float "0"

# Set the icon size of Dock items
defaults write com.apple.dock tilesize -int 36

# Speed up Mission Control animations
defaults write com.apple.dock expose-animation-duration -float 0.15

# Make Dock icons of hidden applications translucent
defaults write com.apple.dock showhidden -bool true

# Do not show recent open applictions
defaults write com.apple.dock "show-recents" -bool false

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# Bottom right screen corner → Mission Control
#defaults write com.apple.dock wvous-br-corner -int 2
#defaults write com.apple.dock wvous-br-modifier -int 0
# Top right screen corner → Put display to sleep
#defaults write com.apple.dock wvous-tr-corner -int 10
#defaults write com.apple.dock wvous-tr-modifier -int 0
# Bottom left screen corner → Desktop
#defaults write com.apple.dock wvous-bl-corner -int 4
#defaults write com.apple.dock wvous-bl-modifier -int 0

###############################################################################
# Spotlight                                                                   #
###############################################################################

if [[ "$RUN_AS_ROOT" = true ]]; then
  # Disable Spotlight indexing for any volume that gets mounted and has not yet
  # been indexed before.
  # Use `sudo mdutil -i off "/Volumes/foo"` to stop indexing any volume.
  sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"

  # Restart spotlight
  killall mds >/dev/null 2>&1
fi

###############################################################################
# Activity Monitor                                                            #
###############################################################################

# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 0

###############################################################################
# Messages                                                                    #
###############################################################################

# Disable smart quotes as it’s annoying for messages that contain code
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

# Disable continuous spell checking
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool false

###############################################################################
# Safari                                                                      #
###############################################################################

# Restore browsing session at launch
defaults write com.apple.Safari AlwaysRestoreSessionAtLaunch -bool true

# Always show the tab bar
defaults write com.apple.Safari AlwaysShowTabBar -bool true

# Show overlay status bar
defaults write com.apple.Safari ShowOverlayStatusBar -bool true

# Show the favorites bar
defaults write com.apple.Safari ShowFavoritesBar-v2 -bool true

# Set default search eingine to DuckDuckGo, in private surfing mode too
defaults write com.apple.Safari SearchProviderIdentifier -string "com.duckduckgo"
defaults write com.apple.Safari PrivateSearchEngineUsesNormalSearchEngineToggle -bool true

# Do not preload top hits in serach bar
defaults write com.apple.Safari PreloadTopHit -bool false

# Open new windows and tabs with the start page
defaults write com.apple.Safari NewWindowBehavior -int 4
defaults write com.apple.Safari NewTabBehavior -int 4
defaults write com.apple.Safari NewTabPageSetByUserGesture -bool true

# Set HomePage to an empty string
defaults write com.apple.Safari HomePage -string "about:blank"

# Enable the Developer menu in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari.SandboxBroker ShowDevelopMenu -bool true

# Disable AutoFill
#defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
#defaults write com.apple.Safari AutoFillCreditCardData -bool false
#defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false

# Enable “Do Not Track”
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

# Warn about fraudulent websites
defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true

# Update extensions automatically
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true

###############################################################################
# App Store                                                                   #
###############################################################################
# Disable in-app rating requests from apps downloaded from the App Store.
defaults write com.apple.appstore InAppReviewEnabled -int 0

###############################################################################
# Time Machine                                                                #
###############################################################################

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Ignore certain paths from Time Machine backupss
defaults write com.apple.TimeMachine SkipPaths -array \
  "~mrolli/.ansible" \
  "~mrolli/.ansible_async" \
  "~mrolli/.cache" \
  "~mrolli/.cargo" \
  "~mrolli/.conda" \
  "~mrolli/.colima" \
  "~mrolli/.docker" \
  "~mrolli/.local" \
  "~mrolli/.npm" \
  "~mrolli/.ollama/models" \
  "~mrolli/.packer.d" \
  "~mrolli/.vagrant" \
  "~mrolli/.vagrant.d" \
  "~mrolli/Downloads/NoBackup"

# Disable local Time Machine backups
#hash tmutil &> /dev/null && sudo tmutil disablelocal

###############################################################################
# Kill/restart affected applications                                          #
###############################################################################

# Restart affected applications if `--no-restart` flag is not present.
if [[ ! ($* == *--no-restart*) ]]; then
  for app in "cfprefsd" "Dock" "Finder" "Mail" "Messages" "Safari" "SystemUIServer" "Terminal"; do
    killall "${app}" >/dev/null 2>&1
  done
fi

printf "Please log out and log back in to make all settings take effect.\n"
