" be iMproved
" This must be first, because it changes other options as a side effect.
set nocompatible              " required by Vundle
filetype off                  " required by Vundle

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" General Plugins
Plugin 'itchyny/lightline.vim'
Plugin 'preservim/nerdtree'
Plugin 'dense-analysis/ale'
Plugin 'maximbaz/lightline-ale'
Plugin 'godlygeek/tabular'
Plugin 'mhinz/vim-signify'
Plugin 'ervandew/supertab'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-sleuth'
Plugin 'tpope/vim-surround'
Plugin 'tmhedberg/SimpylFold'
Plugin 'preservim/tagbar'
Plugin 'jeffkreeftmeijer/vim-numbertoggle'
Plugin 'Yggdroot/indentLine'
Plugin 'pedrohdz/vim-yaml-folds'
Plugin 'luochen1990/rainbow'
" Additional text objects and motions
Plugin 'michaeljsmith/vim-indent-object'
" UltiSnips & Co
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
" Coding specific
Plugin 'editorconfig/editorconfig-vim'
Plugin 'vim-ruby/vim-ruby'
Plugin 'rodjek/vim-puppet'
Plugin 'fatih/vim-go'
Plugin 'mzlogin/vim-markdown-toc'
Plugin 'JamshedVesuna/vim-markdown-preview'

" All of your Plugins must be added before the following line
call vundle#end()
filetype plugin indent on    " required by Vundle
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"change leader to something more
"convenient on a sg keyboard
let mapleader = ","

"setup color scheme
"turn on syntax highlighting
syntax enable
set background=dark
"let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized
" Make comments italic
hi Comment cterm=italic

" always display status line
set laststatus=2

source $HOME/.vim/config/ale.vim
source $HOME/.vim/config/editorconfig.vim
source $HOME/.vim/config/indentline.vim
source $HOME/.vim/config/lightline.vim
source $HOME/.vim/config/markdown-preview.vim
source $HOME/.vim/config/nerdtree.vim
source $HOME/.vim/config/rainbow.vim
source $HOME/.vim/config/signify.vim
source $HOME/.vim/config/ultisnips.vim
source $HOME/.vim/config/vim-better-whitespace.vim

set showcmd                    " show incomplete cmds down the bottom
set noshowmode                 " do not show current mode down the bottom; already shown by lightline
set showmatch                  " set show matching parenthesis
set number                     " show line numbers
set relativenumber             " show relative line numbers by default
set scrolloff=3                " scroll that many lines if cursor leaves viewport
set backspace=indent,eol,start " allow backspacing over everything in insert mode
set history=1000               " store lots of :cmdline history
set incsearch                  " find the next match as we type the search
set hlsearch                   " hilight searches by default
set ignorecase                 " ignore case when searching
set wrap                       " dont wrap lines
set linebreak                  " wrap lines at convenient points
set wildmode=list:longest      " make cmdline tab completion similar to bash
set wildmenu                   " enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~    " stuff to ignore when tab completing

" Swap files in a central location, no swap files amongst project.
set backupdir=~/.vim/swap//
set directory=~/.vim/swap//
set undodir=~/.vim/undofiles//
set undofile
set noswapfile

" Default to Unicode/UTF-8 rather than latin1
set encoding=utf-8

" Default indentation settings
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set smarttab
set autoindent
set cindent           " recommended seting for automatic C-style indentation
set listchars=tab:▶\  " show a symbol for tabs and set colors on next line
highlight SpecialKey ctermfg=white ctermbg=9 guibg=#FF0000

" Indentation settings for certain filetypes
" https://www.arthurkoziel.com/setting-up-vim-for-yaml/
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" some key assignments
nnoremap <F2> :SignifyToggle<CR>:set invnu<CR>
nnoremap <F3> :set invpaste paste?<CR>
nnoremap <F4> :buffers<CR>:buffer<Space>

"folding settings
set foldmethod=indent   "fold based on indent
set foldlevel=99        "open all folds
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default
" toggle code fold with space
nnoremap <space> za

"vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

"some stuff to get the mouse going in term
"set mouse=a
set ttymouse=xterm2

"hide buffers when not displayed
set hidden

" Force markdown for all files with md extension
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
" Fenced languages in markdown
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'ruby', 'puppet']

"jump to last cursor position when opening a file
"dont do it when writing a commit log entry
autocmd BufReadPost * call SetCursorPosition()
function! SetCursorPosition()
    if &filetype !~ 'svn\|commit\c'
        if line("'\"") > 0 && line("'\"") <= line("$")
            exe "normal! g`\""
            normal! zz
        endif
    end
endfunction

" Don't add the comment prefix when I hit enter or o/O on a comment line.
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Split window behaviour
set splitbelow
set splitright

" Split windows navigation
" Arrow keys navigation
nmap <Up> <C-W><Up>
nmap <Down> <C-W><Down>
nmap <Left> <C-W><Left>
nmap <Right> <C-W><Right>
" VIM movement keys
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Reselect visual block after indent (thanks @twe4ked)
vnoremap < <gv
vnoremap > >gv

if &term =~ '256color'
  " disable Background Color Erase (BCE) so that color schemes
  " render properly when inside 256-color tmux and GNU screen.
  " see also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif

" TexLive stuff
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

