# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Insert a blank line between shell prompts
add_newline = true

# Color palette to use
palette = "gruvbox-dark"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$fill\
$all\
$line_break\
$status\
$container\
$character"""

[fill]
symbol = " "

# [custom.foo]
# command = 'echo foo' # shows output of command
# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'

[azure]
disabled = false
format = 'in [$symbol$subscription]($style) '

[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"

[cmd_duration]
format = "[󰚭 $duration]($style) "
show_milliseconds = false
min_time = 5_000
style = "purple"

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "yellow"
truncation_length = 3
# truncation_symbol = "…/"

[git_branch]
style = "blue"
symbol = " "

[git_metrics]
disabled = true

[git_status]
format = "[$ahead_behind $all_status]($style) "
style = "blue"
modified = "~${count}"
deleted = "✘${count}"
up_to_date = "≡"
untracked = "?${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
stashed = "\\$${count}"
staged = "++${count}"
conflicted = "[](red)${count} "

[hostname]
disabled = false
format = "on [$hostname]($style) "
ssh_symbol = " "
ssh_only = false
style = "green"

[terraform]
format = 'via [$symbol$version \($workspace\)]($style) '

[username]
format = "[$user]($style) "
show_always = true
style_user = "orange"

[palettes.gruvbox-dark]
red     = "#cc241d"
red2    = "#fb4934"
green   = "#98971a"
green2  = "#b8bb26"
yellow  = "#d79921"
yellow2 = "#fabd2f"
blue    = "#458588"
blue2   = "#83a598"
purple  = "#b16286"
purple2 = "#d3869b"
aqua    = "#689d6a"
aqua2   = "#8ec07c"
orange  = "#d65d0e"
orange2 = "#fe8019"
gray    = "#928374"
gray2   = "#a89984"
bg      = "#282828"
bg0_h   = "#1d2021"
bg0     = "#282828"
bg1     = "#3c3836"
bg2     = "#504945"
bg3     = "#665c54"
bg4     = "#7c6f64"
fg4     = "#a89984"
fg3     = "#bdae93"
fg2     = "#d5c4a1"
fg1     = "#ebdbb2"
fg0     = "#fbf1c7"
fg      = "#ebdbb2"
