# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "gruvbox-dark"

# [custom.foo]
# command = 'echo foo' # shows output of command
# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'

[azure]
disabled = false
format = 'on [$symbol$subscription]($style) '

[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"

[cmd_duration]
format = "[羽$duration]($style)"
# min_time = 0
show_milliseconds = true
style = "purple"

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "yellow bold"
# truncation_symbol = "…/"

[git_branch]
style = "blue"

[git_metrics]
disabled = true

[git_status]
format = "[$ahead_behind  $all_status]($style) "
modified = "~($count)"
up_to_date = "≡"
untracked = " ?($count)"
style = "blue"

[hostname]
ssh_only = false
ssh_symbol = " "
style = "green"

[terraform]
format = 'via [$symbol$version \($workspace\)]($style) '

[username]
format = "[$user]($style) at "
show_always = true
style_user = "orange"

[palettes.gruvbox-dark]
red     = "#cc241d"
red2    = "#fb4934"
green   = "#98971a"
green2  = "#b8bb26"
yellow  = "#d79921"
yellow2 = "#fabd2f"
blue    = "#458588"
blue2   = "#83a598"
purple  = "#b16286"
purple2 = "#d3869b"
aqua    = "#689d6a"
aqua2   = "#8ec07c"
orange  = "#d65d0e"
orange2 = "#fe8019"
gray    = "#928374"
gray2   = "#a89984"
bg      = "#282828"
bg0_h   = "#1d2021"
bg0     = "#282828"
bg1     = "#3c3836"
bg2     = "#504945"
bg3     = "#665c54"
bg4     = "#7c6f64"
fg4     = "#a89984"
fg3     = "#bdae93"
fg2     = "#d5c4a1"
fg1     = "#ebdbb2"
fg0     = "#fbf1c7"
fg      = "#ebdbb2"
