---
- name: Create different directories
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
  loop:
    - ~/.config
    - ~/.local
    - ~/.ssh/

- name: Find .config files
  find:
    paths: ~/.dotfiles/config/
    recurse: no
    file_type: any
    hidden: yes
  register: dot_config

- name: ~/.config/
  file:
    src: "{{item.path}}"
    dest: "~/.config/{{item.path | basename}}"
    state: link
    force: true
  loop: "{{ dot_config.files }}"
  loop_control:
    label: "~/.config/{{item.path | basename}}"

- name: Setup additional symlinks
  file:
    path: "{{ item.path }}"
    src:  "{{ item.src }}"
    state: link
    force: true
  loop: "{{ dotfiles_additional_symlinks }}"

# - name: .ssh/config
#   copy:
#     src: ~/.config/.ssh.config
#     dest: ~/.ssh/config
#     mode: u=rw,o=,g=

# - name: .ssh/config/control
#   file:
#     path: ~/.ssh/control
#     state: directory
#     mode: u=rwx,o=,g=

# - name: gpg-agent.conf
#   copy:
#     dest: ~/.gnupg/gpg-agent.conf
#     content: "pinentry-program /bin/pinentry"
