# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Set XDG defaults for those apps honoring these settings but having no defaults
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Zsh config dir
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export ZDATADIR="${XDG_DATA_HOME:-$HOME/.local/share}/zsh"
export ZCACHEDIR="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"

# Highlight section titles in manual pages in yellow.
export LESS_TERMCAP_md="$(tput setaf 136)"
# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X'

# GPG env var used by gpg-agent
export GPG_TTY=$(tty)

# Set preferred editor
export EDITOR="nvim"
export SVNEDITOR="nvim"
export VISUAL="nvim"

# Make less the default pager, and specify some useful defaults.
less_options=(
	# If the entire text fits on one screen, just show it and quit. (Be more
	# like "cat" and less like "more".)
	--quit-if-one-screen

	# Do not clear the screen first.
	--no-init

	# Like "smartcase" in Vim: ignore case unless the search pattern is mixed.
	--ignore-case

	# Do not automatically wrap long lines.
	--chop-long-lines

	# Allow ANSI colour escapes, but no other escapes.
	--RAW-CONTROL-CHARS

	# Do not ring the bell when trying to scroll past the end of the buffer.
	--quiet

	# Do not complain when we are on a dumb terminal.
	--dumb
);
export LESS="${less_options[*]}";
unset less_options;
export PAGER='less';

# Vagrant/Packer specific
export PACKER_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/packer"
