# Setup Zinit plugin manager
ZINIT_HOME="$XDG_DATA_HOME/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname "$ZINIT_HOME")"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "$ZINIT_HOME/zinit.zsh"

# Explicitly set vi mode for key bindings
bindkey -v
export KEYTIMEOUT=1
# search history with up/down arrows based on what's typed in the prompt
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Go to folder path without using cd
setopt AUTO_CD
# Turn off all beeps
unsetopt BEEP
# Turn off autocomplete beeps
#unsetopt LIST_BEEP

# Source my config files
source "$ZDOTDIR/plugins.zsh"
source "$ZDOTDIR/history.zsh"
if [ "$(uname -s)" = "Darwin" ]; then
  source "$ZDOTDIR/macos.sh"
fi
source "$ZDOTDIR/completion.zsh"
source "$ZDOTDIR/aliases.sh"
source "$ZDOTDIR/functions.sh"
if command -v conda &>/dev/null; then
  source "$ZDOTDIR/conda.zsh"
fi

# build the PATH variable
PATH=~/.local/bin:$PATH

# Add Go binary path
[ -d "$HOME/go/bin" ] && PATH="$HOME/go/bin:$PATH"

# Make vagrant vcloud token available
[ -f "$HOME/.vagrant.d/vcloud_token.sh" ] && source "$HOME/.vagrant.d/vcloud_token.sh"

# build prompt
eval "$(starship init zsh)"
