#!/usr/bin/env bash

backup_item=(
  Archiv
  Comics
  Dokumente
  Ebooks
  Music
)

disk_data_path=/Volumes/Data
disk_backup_path=/Volumes/Backup/Backup

if [ ! -d $disk_backup_path ] || [ ! -d $disk_data_path ]; then
  echo "Backup volumes not mounted. Exiting..."
  exit 1
fi

print_usage() {
  echo "Usage: ${0} [-vn]"
  exit 0
}

verbosity="-q"
dryrun=""

while getopts hnv option; do
  case "${option}" in
  h) print_usage ;;
  n) dryrun="-n" ;;
  v) verbosity="--progress --stats" ;;
  ?) print_usage ;;
  esac
done

rsync_cmd="$(brew --prefix)/bin/rsync -av --delete ${verbosity} ${dryrun}"

if [ "$verbosity" != "-q" ]; then
  echo "Using Rsync command: ${rsync_cmd}"
fi

for dir in "${backup_item[@]}"; do
  echo -e "\n\n----- Syncing $disk_data_path/$dir/ to $disk_backup_path/$dir/"
  $rsync_cmd "$disk_data_path/$dir/" "$disk_backup_path/$dir/"
done
