#!/usr/bin/osascript
on run
  if application "Music" is running then
    tell application "Music"
      if class of current playlist is not user playlist then return

      set delete_this to current track
      set track_artist to artist of current track
      set track_name to name of current track
      set playlist_name to name of current playlist

      next track
      try
        delete delete_this
      end try

      set display to "Removed \"" & track_artist & " - " & track_name & "\" from playlist " & playlist_name
    end tell
  end if
end run
