# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Keep plenty of history.
HISTFILESIZE=1000000
HISTSIZE=1000000

# Build path
PATH=~/bin:$PATH

# colored ls output
alias ls='ls -G'
# start SMclient on remote host
alias SMclient='ssh gpfs03-local SMclient'

# environment variables
export LSCOLORS=Dxfxcxdxbxegedabagacad
export TERM=xterm-256color
export EDITOR=vim
export SVNEDITOR=vim

# setup bash completion
source ~/.tmux-completion.sh
source ~/.vagrant-completion.sh
source ~/.git-completion.sh
source ~/.git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto verbose"

# rbenv stuff
if which rbenv >/dev/null 2>&1; then eval "$(rbenv init -)"; fi

# build command prompt
ps1_prompt() {
    local ps1_exit=$?
    local ps1_status="\!"
    local YELLOW="\[\033[1;33m\]"
    local GREEN="\[\033[32m\]"
    local RED="\[\033[31m\]"
    local NOCLR="\[\033[0m\]"

    # define user/hosts and directory string
    if [ $UID -eq 0 ]; then
        local HOSTCOLOR=$RED
        local PSEND="#"
    else
        local HOSTCOLOR=$GREEN
        local PSEND="\$"
    fi
    local ps1_host=" ${HOSTCOLOR}\u@\h${NOCLR}"
    local ps1_dir=" ${YELLOW}\W${NOCLR}"

    # setup exit status string
    if [ $ps1_exit -ne 0 ]; then
        local ps1_status="${RED}\!${NOCLR}"
    fi

    # setup git repo string
    ps1_git=""
    if test "$(type -t __git_ps1)" = "function"; then
        ps1_git="${RED}"$(__git_ps1)"${NOCLR}"
    fi

    PS1="${ps1_status}${ps1_host}${ps1_dir}${ps1_git} \$ "
}
# preserve earlier PROMPT_COMMAND entries
PROMPT_COMMAND="ps1_prompt;$PROMPT_COMMAND"

# finally export built PATH variable
export PATH=$PATH

