# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Keep plenty of history.
HISTFILESIZE=1000000
HISTSIZE=1000000

# Build path
PATH=~/bin:$PATH
PATH=/usr/local/bin:$PATH
PATH=/usr/local/git/bin:$PATH
[ -d /Applications/Xcode.app/Contents/Developer/usr/bin  ] && PATH=$PATH:/Applications/Xcode.app/Contents/Developer/usr/bin/

# some useful aliases
alias ls='ls -G'
alias dir='ls -al'

# environment variables
export LSCOLORS=Dxfxcxdxbxegedabagacad
export TERM=xterm-color
export EDITOR=vim
export SVNEDITOR=vim
export ACTIVEMQ_HOME=/Users/mrolli/Developer/projects/ds-fs12/apache-activemq-5.6.0

# setup git-achievements
PATH=$PATH:~/bin/git-achievements
alias git="git-achievements"

# setup git completion
source ~/.git-completion.sh
source ~/.git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto verbose"
PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[33m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '

# finally export built PATH variable
export PATH=$PATH
