#!/usr/bin/env bash

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto verbose"

# build command prompt
ps1_prompt() {
    local ps1_exit=$?
    local ps1_status="\!"
    local YELLOW="\[\033[1;33m\]"
    local GREEN="\[\033[32m\]"
    local RED="\[\033[31m\]"
    local LRED="\[\033[1;31m\]"
    local LBLUE="\[\033[1;34m\]"
    local BLUE="\[\033[34m\]"
    local NOCLR="\[\033[0m\]"
    # see https://misc.flogisoft.com/bash/tip_colors_and_formatting

    # define user/hosts and directory string
    if [ $UID -eq 0 ]; then
        local HOSTCOLOR=$RED
        local PSEND="#"
    else
        local HOSTCOLOR=$GREEN
        local PSEND="\$"
    fi
    local ps1_host=" ${HOSTCOLOR}\u@\h${NOCLR}"
    local ps1_dir=" ${YELLOW}\W${NOCLR}"

    # setup exit status string
    if [ $ps1_exit -ne 0 ]; then
        local ps1_status="${RED}\!${NOCLR}"
    fi

    # setup git repo string
    ps1_git=""
    if test "$(type -t __git_ps1)" = "function"; then
        ps1_git="${RED}"$(__git_ps1)"${NOCLR}"
    fi

    # setup conda env
    ps1_conda=""
    if [ ! -z $CONDA_DEFAULT_ENV ]; then
      ps1_conda=" ${LBLUE}(${CONDA_DEFAULT_ENV})${NOCLR}"
    fi

    PS1="${ps1_status}${ps1_conda}${ps1_host}${ps1_dir}${ps1_git} \$ "
}
# preserve earlier PROMPT_COMMAND entries
PROMPT_COMMAND="ps1_prompt;$PROMPT_COMMAND"

