#!/usr/bin/env bash

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set standby delay to 3 hours; default: 4200
sudo pmset -a standbydelay 10800

# Disable the sound effects on boot
#sudo nvram SystemAudioVolume=" "
# Disable find my mac feature
#nvram -d fmm-computer-name
#nvram -d fmm-mobileme-token-FMM

# Common Menu bar items:
#  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
#  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
#  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
#  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
#  "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
#  "/System/Library/CoreServices/Menu Extras/User.menu" \
#  "/System/Library/CoreServices/Menu Extras/Volume.menu" \
#  "/System/Library/CoreServices/Menu Extras/VPN.menu" \
# Menu bar: hide some icons
defaults write com.apple.systemuiserver dontAutoLoad -array \
  "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
  "/System/Library/CoreServices/Menu Extras/User.menu"
# Menu bar: show some icons
defaults write com.apple.systemuiserver menuExtras -array \
  "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" \
  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
  "/System/Library/CoreServices/Menu Extras/Clock.menu" \
  "/System/Library/CoreServices/Menu Extras/Displays.menu" \
  "/System/Library/CoreServices/Menu Extras/VPN.menu"

# Show percentage in battery menu bar
defaults write com.apple.menuextra.battery ShowPercent -bool true

# Always show scrollbars
# Default: "WhenScrolling"
# Possible values: "WhenScrolling", "Automatic" and "Always"
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -book true

# Save to disk (not to iCloud) by default
#defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs complete
#defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the “Are you sure you want to open this application?” dialog
#defaults write com.apple.LaunchServices LSQuarantine -bool false

# Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Display ASCII control characters using caret notation in standard text views
# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
#defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

# Disable Resume system-wide
#defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

# Disable automatic termination of inactive apps
#defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

