#!/usr/bin/env bash

###############################################################################
# Keyboard and input                                                          #
###############################################################################

# Enable full keyboard access for all controls
# (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
# Follow the keyboard focus while zoomed in
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Set a faster keyboard repeat rate
# Default: 30
defaults write NSGlobalDomain KeyRepeat -int 6
# Default: 68
defaults write NSGlobalDomain InitialKeyRepeat -int 25

# Use fn to invoke itunes controls/mission control
# Default: flase
defaults write NSGlobalDomain com.apple.keyboard.fnState  -bool true

#- Set language and text formats
#-defaults write NSGlobalDomain AppleLanguages -array "de-CH" "en-CH"
#-defaults write NSGlobalDomain AppleLocale -string "de_CH"
#-defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
#-defaults write NSGlobalDomain AppleMetricUnits -bool true

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
sudo systemsetup -settimezone "Europe/Zurich" > /dev/null

# Disable a lot auto-correction stuff; default: absent
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticTextCompletionEnabled -bool true

# Stop iTunes from responding to the keyboard media keys
#launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

